#!/bin/bash

# Ganti 'TOKEN_BOT_ANDA' dengan token bot yang diberikan oleh BotFather
TOKEN="6159420338:AAFYFkZ8g79vp0GQTTbgbvnsvIQC2MR2wz8"

# Ganti 'CHAT_ID_TUJUAN' dengan ID obrolan tempat Anda ingin mengirim dokumen
CHAT_ID_TUJUAN="431283315"

# Ganti 'LOKASI_FILE_ANDA/dokumen.pdf' dengan lokasi dan nama file dokumen yang ingin Anda kirim
FILE_PATH="/var/lib/vnstat/vnstat.db"

CAPTION="*Backup Database Vnstat RavaVPN*  /var/lib/vnstat/vnstat.db"

# Menggunakan multipart/form-data untuk mengirim file
curl -F document=@"$FILE_PATH" -F caption="$CAPTION" -F parse_mode="Markdown" "https://api.telegram.org/bot$TOKEN/sendDocument" -F chat_id="$CHAT_ID_TUJUAN"

